services:

  redis:
    image: redis:7-alpine
    container_name: redis

    restart: unless-stopped

    networks:
      - browser-platform-net

  session-service:
    build:
      context: ./session-service

    container_name: session-service

    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - redis

    networks:
      - browser-platform-net

networks:
  browser-platform-net:
    external: true